trigger:
  - main

pr: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/azure-pipeline-templates

extends:
  template: pipeline-fe-library.yaml@templates
  parameters:
    libraryName: "cp-primeng-table"
    installCommand: "install --legacy-peer-deps"
